### ISSUE TITLE
Extension Reporting Mechanism

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#1]
The framework must provide a way for extensions to report the data they collect in a way that can be easily reviewed by a site owner.

This should include:

- A standardized manifest for reporting data (see https://github.com/joomla/joomla-cms/issues/20140 for an example and further discussion)
    - Information retained in the database
    - Cookies
- Event hooks where plugins can also process this data
- A screen in a `com_privacy` component to display this information

**Comment by aDaneInSpain** [comment]
Some things to consider:

- Should extension developers specify if data should be deleted or anonymized?
- Should extension owners be able to provide their own methods for anonymization and deletion?
- Should extension owners be able to indicate a whole row in a table (as opposed to just a field) should be deleted/anonymized?

**Comment by mbabker** [comment]
Yes, yes, and no.

The extension developer/owner will know best what purpose their extensions are serving and the data they are collecting, and inherently should be able to best specify whether data by default should be able to be fully deleted, anonymized, or not touched at all (in contexts where other legal requirements would call for that).

As an anonymization/deletion process would be triggering data updates, it should also be possible to hook into that extension's own system to handle said updates (which would include the potential of triggering plugin events, which may not be using the same events that core uses).

As for full row anonymization, I would not do this; it should be a by-field operation (columns like created/modified dates don't really need to be random, columns which should be foreign keys should still have correct data integrity, etc.).

**Comment by aDaneInSpain** [comment]
As for full row deletion it would be mainly for a log system for instance. Delete all rows with the user_id = x so that you do not end up with a log table full of empty fields. But your call.

**Comment by mbabker** [comment]
To me that's something that can be left up to the extension.  Because odds are if you're requesting data be deleted, you're going to just remove the full row and not only the fields containing privacy related data for exactly the reason you've pointed out.  So the reporting mechanism reports sensitive fields but the code running a delete operation would make the smart decision on deleting a field versus row.

**Comment by aDaneInSpain** [comment]
So you are saying that to delete a full row the extension should provide it's own delete method (plug-in)? I guess that makes sense, although the more Joomla can handle this the more likely it will be implemented properly by 3rd party developers (who tend to like cutting corners).

**Comment by brianteeman** [comment]
core joomla should never touch an extension's code or data

**Comment by mbabker** [comment]
The default delete logic would basically be a series of `UPDATE foo SET bar = NULL, baz = ''` type queries.  Depending on what data is in the manifest, we aren't going to be able to do things like:

- Load a model from a component's MVC
- Load a JTable object from a component

So all we can do is empty fields.  This is why the system needs to be hookable/extensible, where a delete method can be specified.  Conceptually this isn't going to be much more complex than [the default case in `Joomla\CMS\Form\Form::filterField()`](https://github.com/joomla/joomla-cms/blob/e99b38dc22fc61ebaa1384cda2c3a60379a1383b/libraries/src/Form/Form.php#L1548-L1576) where core checks if there is a valid callback structure in place and if not then default to our sane defaults.

Or, we don't touch any data ourselves and make the entire delete/anonymize process run as a series of plugin events (`onProcessUserAnonymize`, `onProcessUserDelete`, etc.).  If you don't have a plugin then you don't integrate into the system.  Thinking about it some having the entire system be plugin driven would mean we don't have to have a separate manifest file (XML) or deal with some of the quirks that would come with specifying callback functions in XML (trying to load files for example).  So for the reporting side of things, we dispatch `onPrivacyCollectSensitiveFields` and `onPrivacyCollectCookies` events that each return a collection of objects with the data in our structure (using your XML example as a good starting point for that definition).

* all event names are just examples and definitely not final 😃

**Comment by aDaneInSpain** [comment]
So you are saying that all deletion in all extensions should be performed by the extensions then. Hmmm... it is not as smooth as I had hoped it would be which leads me to believe that if a 3rd party GDPR extension gains popularity and it offers to do the deleting for the extensions it might become the de facto standard over the Joomla core which would be a shame.

The core already deletes tables when a component is uninstalled (if the component tells the core to do so) - this would be no different. If the component supplies a GDPR config file then the core can "delete private user data" on user delete event. 

If you leave it up to each extension then each extension developer will have to install and activate a system plug-in that detects "onUserBeforeDelete" and then perform their clean up on that event. They can already do that now and as such we need no connection with 3rd party extensions. 

This is the wrong approach in my opinion. The core **should** be performing the deletion/anonymization when a user is deleted to make it as easy for 3rd party developers to implement GDPR compliance as possible.

**Comment by mbabker** [comment]
I am aiming a bit conservatively right now.  Because I don't want core blindly touching data and I'm not entirely convinced that core needs to be entirely responsible for crafting the SQL queries it takes to handle the update/delete actions (especially because in the case of a deletion there may be other actions that need to be taken to remove the record; in one application I maintain if we were to delete a row from the users table there are 4 tables with direct FK relations that would need to be checked to either null the key or delete the row, and 2 of those have cascading relations to other tables as well).  So personally I do believe it is in our best interest to look toward a plugin driven solution for these actions versus hardcoding some logic.  That's not to say, as I pointed out, we can't have a default case where we CAN do something basic, but I really feel like using that code path would have to be an exception to the rule and not the standard.

If you haven't yet, take a look into WordPress' privacy tools that are going into their release coming out this month ([this commit](https://github.com/WordPress/wordpress-develop/commit/cdb3f044c46eb03069ff133cdc8f3cd14042d2af) is where the erasure framework was added, of course there have been modifications since).  It is a callback/plugin driven system.  That implementation strengthens my belief that our system being plugin driven versus us writing and executing SQL queries on our own is in our best interests.  Even if we did try to do the queries on our own, we would still have to emit events for the reasons I pointed out above (needing to handle cleanup on related records).

**Comment by laoneo** [comment]
To stay save I would also prefere to forward the job to the extension. It can then also cleanup some relations if required or do some other cleanup tasks.

**Comment by Ruud68** [comment]
Hi, as extension developer I would favor a plugin approach and by doing that make it my responsibility to provide the information or delete the information. Especially when there are linked tables things could get messy. 'Mess' that I would have to give support to when things stop working as expected. The JED could have a badge stating the extension's GDPR compliancy (simple yes / no) just like there is now an indicator if the Joomla updater is used.

**Comment by JoomliC** [comment]
I think it could be plugin driven system (by 3rd Party extension) with manifest install statement as it is for update server to get the information in com_privacy.

- 3rd party extension declare private data that could be stored (eg. <privacy>list of informations collected by extension, purpose...</privacy>)
- Component Privacy collect this information from install/update manifest (and list it as it is for Update Sites, by giving the needed information. Table #__privacy_extensions)
- 3rd party extension provide a privacy plugin (maybe creating a group for privacy plugin ?)
- Allow the 3rd party privacy plugin to communicate/link information to com_privacy to complete core process information given to user.

Just an "not-clear" idea... but maybe a "Update-sites" like process ?

**Comment by sandewt** [comment]
Consideration

Perhaps this topic has already been discussed?

IP addresses may fall according to the GDPR on privacy sensitive information. These are stored in the log file(s) by Joomla.

It would be nice if there is a possibility to keep it for a limited time. And not endlessly, as is the case now. Then remove it.

**Comment by brianteeman** [comment]
Which log files are you talking about? If you mean the server (apache)  log files then that is nothing to do with Joomla. How long they are stored etc is something for you to discuss with your web host. Joomla doesnt have any control over them and nor can it control them

**Comment by sandewt** [comment]
@brianteeman 

I mean the log files in `...\Joomla\administrator\logs\` e.g. `error.php`
```
#
#<?php die('Forbidden.'); ?>
#Date: 2018-05-01 11:06:28 UTC
#Software: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#Fields: datetime	priority clientip	category	message
2018-05-01T11:06:28+00:00	INFO ::1	joomlafailure	Username and password do not match or you do not have an account yet.
2018-05-01T11:09:06+00:00	INFO ::1	joomlafailure	Username and password do not match or you do not have an account yet.
2018-05-01T11:10:40+00:00	INFO ::1	joomlafailure	Username and password do not match or you do not have an account yet.
```

**Comment by brianteeman** [comment]
@sandewt please create a NEW issue for that - it is nothing to do with "Extension Reporting Mechanism "

**Comment by JoomliC** [comment]
> I don't see the point in having a standalone manifest file with this information also

I didn't mean in a new xml file, but in the manifest install file used by all existing extensions.
This allow to collect it eg. in extensions table or linked com_privacy table, to allow to display easily provided information in com_privacy...

But maybe you see better nothing like that, and a plugin event handler in com_privacy control panel to allow plugin to inform user there what the 3rd party do and can do ?

It is just to know/find the best way for Joomla to know from each 3rd party extensions if they integrate with Joomla privacy, and/or what they do/not-do.

**Comment by mbabker** [comment]
> But maybe you see better nothing like that, and a plugin event handler in com_privacy control panel to allow plugin to inform user there what the 3rd party do and can do ?
> 
> It is just to know/find the best way for Joomla to know from each 3rd party extensions if they integrate with Joomla privacy, and/or what they do/not-do.

I'm leaning toward just doing as much in the plugin as possible since we're essentially going to require a new plugin in the `privacy` group, I'm thinking we should steer this so you have one plugin fora complete extension package (so there'd be a `plg_privacy_content` covering `com_content`, the voting plugin, and whatever other elements are needed), plus if we can have one plugin handle reporting requirements for multiple individual extensions that would be a bit more efficient than having a separate standalone manifest file in `com_content`, the voting plugin, and every individual extension.

**Comment by dirigit** [comment]
After reading a bunch of threads and related documentation as well as getting a lot of education without becoming a guru I don't want to disturb much but, currently Joomla has a problem with already existing laws in several regions of the world:

At the moment there is no privacy by design of core system.

GDPR is only one issue on the way to become compliant. Being released 2016 it got the rock rolling now. There is an upcoming ePrivacy regulation which is not released and active as of now (should become active with GDPR).

In draft of this regulation there is a clear requirenment to get consent of user (visitor) before anything is saved at user side (cookie, whatever). No consent - no storage. Hard times especially for advertising industry ...

GDPR says consent of children is invalid when they are to young (min. age EU general: 13, Austria: 14, Germany: 16, ...).

Have a look at U.S.A. and you'll find different minimum ages to be able to accept consent as well. I stumbled over California  to name only one example for such requirenments in existing and active law.

Unsorted list of further thoughts:

Anonymous storage of IPs - simple solution could be to introduce a setting and related function to say i.e. we invalidate xy bytes of IP v4 addresses. IP v6 is next to be considered. Have a look at Matomo (was Piwik) for an example of implementation.

Plugin based handling - what about cache?
AFAIR it needs a module to manipulate cache of Joomla.

Deletion of user data - isn't it enough to make data invalid e.g. with Xs to avoid empty rows?
Backups of database are a problem of website owner.

Exporting user data to fullfill requirenment of GDPR in relation to transfer - AFAIK csv export is sufficient. Performing an export is no task for users - it's a task of administration. Should be a core functionality in relation to Joomla users.

Extensions might save user data for themself and must handle those data in relation to law to be compliant. I.e. a shop forcing a customer to register at Joomla can not be compliant (GDPR 7.4 and 6.1.1). Keywords are "free" and "coupling" in this relation. Nevertheless a customer could be a Joomla user as well.

Different cookies - there are multiple kinds of cookies possible. There should be core functionality to be able to suppress system cookies and extension cookies at least with help of Joomla's core (privacy by design).

More related to extension developers:
Links to facebook and the like - a nice (and working) approach for using it in accordance to GDPR and similar regulations can be found at https://github.com/heiseonline/shariff.

**Comment by brianteeman** [comment]
@dirigit thank you for taking the time to comment. It would be really helpful if you could check all the existing issues to see if your issues are already listed and being addressed AND if any of them are not then to create a brand new issue report for each of them

**Comment by aDaneInSpain** [comment]
We will end up with a lot of duplicated and copy pasted code if each extension (including the core ones) are to handle their own clean up.

To me this should simply be adding a <personal-data> section to the manifest of a plug-in and the core should handle everything else (unless the manifest specifically supplies it's own methods for deleting).

Loading plug-ins for each extension would potentially lead to performance degradation and definitely lead to duplicated code which is never good.

**Comment by dirigit** [comment]
@brianteeman Thank you for kind response.

Sadly there seems to be a general tendence to introduce privacy as an add-on to Joomla. Such a solution would be a patchwork with unforseeable risks from beginning. Risk can be performance, security, take whatever you want. Dealing with cache is only one issue related to technical problems.

For me it looks like trying to bridle the horse from behind. Giving privacy same priority like security would be a long term solution IMHO.

Now, to get knowledge about what has to be done and what has been implemented there should be kind of a list of requirenments. I try to write some lines here and try to take all issues found in several regions of the world.

1. Free consent of visitor before setting any cookie or the like
1.a Problem: Age of visitor is an issue in multiple regions
1.b User can change mind and wants to change previous decission

2. Keep collected data at it's bare minimum needed to perform a task. Site owner is responsible!
2.a Invalidation at IP collection (IP v4, IP v6)!

In case of acceptance

3. Information to user - what kind of data is saved on visitors side (cookies etc) or in system in detail

4. Export all user related data (common format like csv).

5. Delete user data - Invalidation should be sufficient to avoid technical problems in db (autoincrement :()

To be continued. I will try to find out what is implemented at the moment when time permits.

cu, diri

**Comment by brianteeman** [comment]
@dirigit again please review what has already been noted before commenting further. Most if not all has already been addressed.

**Comment by jomres** [comment]
I'll back this approach. As Jomres works on both WP and J natively I've had to add my own methods for reporting and anonymising data. Hooking into J should, for me, be a formality. Just tell me to anonymise, give me a cms user id and I can handle the rest. 

> Or, we don't touch any data ourselves and make the entire delete/anonymize process run as a series of plugin events (onProcessUserAnonymize, onProcessUserDelete, etc.)

**Comment by mbabker** [comment]
https://github.com/joomla-projects/privacy-framework/pull/37 is the first extension integration point being proposed, and probably the easiest but to me one of the most beneficial as this is going to provide to site administrators a central location to get specific details about what both the core platform and their installed/enabled extensions are doing as it relates to potential privacy related matters.  I also think as a lower priority feature we should think about a similar type of hook for the frontend at least when requesting your information be removed/anonymized so there's some clarity for the requesting user as to what exactly is going to happen, but that'll be long after all the other admin and architecture stuff is in place.

I'll get to data processing events next (#3 and probably other stuff that hasn't been covered in an issue yet).

**Comment by ankush-maherwal** [comment]
I also favour plugin approach to handle the data deletion requests of the site users, depending on the data the extension stores the extension developers can implement a plugin to delete or anonymize the user's data.

We have documented a solution around deboarding the users from the site, the doc specifies the way to store the consents of the users and the triggers which can be used in deleting or anonymizing the user's data.

https://github.com/techjoomla/user-deboarding/wiki

**Comment by mbabker** [comment]
We should be covered now.
