### ISSUE TITLE
Submitting Requests

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#10]
Separate from #3 and dependent upon #9

The intent here is to help make it easier for users to submit information requests, such as requesting a copy of their associated data or a request to be deleted.  To get the requests into the system, I envision two ways of accomplishing this:

- User contacts a site admin outside the site (phone call, email, etc.) and the admin can create the request in the backend
- User can use a dedicated form on the frontend to submit the request
    - To alleviate spam concerns a site owner could configure this form to be accessible to authenticated user accounts only, which isn't foolproof but will help in many cases I would imagine

Regardless of entry method, as a security measure because a user's personal information is being worked with (which depending on the site in question could be something more sensitive in nature than a name, such as a social security number in the US), there should be a double opt-in workflow here.  This should operate similar to a password reset workflow (user completes form, is sent an email with a verification token/link that they use to confirm request).  A non-confirmed request shouldn't be blocked from being acted upon, but a confirmed versus pending confirmation request will have different statuses when shown in the request list.

**Comment by brianteeman** [comment]
I am wondering if it should be even more strict that the password change request verification process

(not sure how)

**Comment by mbabker** [comment]
> I am wondering if it should be even more strict that the password change request verification process

The presentation you linked in #7 does mandate that you verify the identity of the person.  At a minimum I would say that does include the double opt-in but not sure yet how else we could fulfill that.

**Comment by mbabker** [comment]
Completed via #15 and #33
