### ISSUE TITLE
Content - confirm consent plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#102]
If you have a privacy article defined then it is being wrapped around the short privacy text and not the label.

The offending code is

```
		// When we have a article just add it arround to the text
		if ($privacyarticle)
		{
			HTMLHelper::_('behavior.modal');

			$consentboxText = $this->getAssignedArticleUrl($privacyarticle, $consentboxText);
		}

```

Sorry - don't know how to fix it

**Comment by brianteeman** [comment]
same issue on the create request form

**Comment by joomdonation** [comment]
@brianteeman Could you please check to see whether https://github.com/joomla-projects/privacy-framework/pull/111 solved this issue?
