### ISSUE TITLE
Urgent Requests

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#104]
It is very confusing because we have no indicator in the request manager or dashboard what is in an urgent request. So if you follow the alert on the control panel that you have 1 urgent request and then see 6 requests people are bound to raise a bug report

I was thinking of something like this but no idea how to code it
<img width="479" alt="chrome_2018-06-17_23-58-43" src="https://user-images.githubusercontent.com/1296369/41512901-6626a370-728a-11e8-9ff3-f4605630d6ef.png">

**Comment by mbabker** [comment]
See #106
