### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#11]
In theory (and especially if you are using role based acl) you could have a site with the following scenario

- admin with only access to the ecommerce component
- admin with only access to the newsletter component
- admin with only access to the membership component

For the privacy component to work you would need to have a user with access to all the information otherwise someone with only newsletter access would see data that they were not intended to see from the ecommerce component

So "maybe" the solution is to restrict access to this component to super users like akeeba does

**Comment by brianteeman** [comment]
Another real world example would be on joomla.org. The volunteer portal says 

> According to section 4.03 of the Open Source Member By-laws your address is required as Member of a team. The provided mailing address is only **visible for the Secretary of Open Source Matters** and only required for active members of a team.

**Comment by peteruoi** [comment]
Maybe a new predefined role DPO between administrator and super administrator?

**Comment by brianteeman** [comment]
I wouldnt do it that way but use a role that can be applied to a specific user or users. You many not want to give the DPO access to other aspects of the site so a hierarchical option would not be appropriate

**Comment by mbabker** [comment]
> So "maybe" the solution is to restrict access to this component to super users like akeeba does

My initial thought was to go for that too.  Because exactly as you pointed out, there are a massive number of scenarios to take into account where someone without read access to another portion of the site could see some sensitive data, therefore the safest option would be restricting to super users who should already be entrusted to see all the things.

**Comment by JoomliC** [comment]
I will go too for superuser (Controller ?) as default VS others with admin access (Processor?).

Maybe a related information about this point in GDPR, Article 18 - Right to restriction of processing:  
https://gdpr-info.eu/art-18-gdpr/

We can then maybe just have additional access option like this :  
`<action name="core.privacy" title="JACTION_PRIVACY" description="JACTION_PRIVACY_COMPONENT_DESC" />`
Which one could be set in each 3rd party component?

**Comment by zero-24** [comment]
Implementation done here: https://github.com/joomla-projects/privacy-framework/pull/13
