### ISSUE TITLE
Configure a users action logs

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#110]
I can configure the action logs that I will receive on the front end via my edit profile page and in the admin via the my profile link in the top right.

But I cannot configure it from the admin user menu - which means I cannot configure it for any other super user

adding com_users.user here works
https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/plugins/system/actionlogs/actionlogs.php#L80

But then we also need to NOT display it when the user is not a super user. As it is 1am here and I have matchsticks in my eyes I cant find out how to do that - must be simple

**Comment by joomdonation** [comment]
Your propose change should work. We already have code to check and only display the settings to user who has view logs permission enabled (only Super Users has this permission by default), see https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/plugins/system/actionlogs/actionlogs.php#L85

So just go ahead to make the PR to fix this issue, please.

**Comment by alikon** [comment]
this should be solved now by #113 & #116
