### ISSUE TITLE
System - Actions Log: Warning message displayed when plugin enabled

### ISSUE THREAD

**Issue by Sandra97** [joomla-projects/privacy-framework#119]
When this plugin is enabled, a warning message is displayed when I open a plugin, a module, a menu item...
`Warning JUser: :_load: Unable to load user with ID: 117 `
Note that the ID has nothing to do with a user ID, it's each time the ID of the plugin, or module, or menu item I open.

If I disable the _System - Actions_ Log Plugin, the warning disappears.

_(I installed it 3 or 4 times, using different servers, same result)._

**Comment by joomdonation** [comment]
It causes by this PR https://github.com/joomla-projects/privacy-framework/pull/116. Ping @alikon

**Comment by mbabker** [comment]
The `in_array($formName, $allowedFormNames)` check should be done before trying to load the user record to check if `$canView`.

**Comment by alikon** [comment]
yes my fault  sorry here is a fix  #120

**Comment by alikon** [comment]
it always a pleasure to work with you folks, especially in a so fast way :smile:
