### ISSUE TITLE
Plugin System - Privacy Consent. Cannot log out if I don't agree.

### ISSUE THREAD

**Issue by ReLater** [joomla-projects/privacy-framework#122]
Maybe an expected behavior but I don't think that it's OK.

### Steps to reproduce the issue
- Install privacy-framework package with testing sample data.
- Activate plugin `System - Privacy Consent`
- Log in in frontend (module `Login Form` in right sidebar)
- Automatic redirect to profile page with consent checkbox `Web Site Privacy`
- Do nothing
- Try to log out (module `Login Form` in right sidebar).

### Expected result
I can log out because I'm not willing to agree at the moment (no time to read the policies or whatever).

### Actual result
I cannot log out and the page always redirects to the profile page.

**Comment by brianteeman** [comment]
Isnt this the same behaviour as when a user who has had the password reset turned on by an admin thn log in?

**Comment by mbabker** [comment]
[This line](https://github.com/joomla-projects/privacy-framework/blob/ca483c7a74e23fd898a71bdf553e0dd422c90573/libraries/src/Application/SiteApplication.php#L230) has the whitelisted tasks to "bypass" the reset check, the logout task is one of them.  Looks like the plugin needs to add the "profile.apply" and "user.logout" tasks.

**Comment by joomdonation** [comment]
PR https://github.com/joomla-projects/privacy-framework/pull/123 should fix it.

**Comment by ReLater** [comment]
PR 123 fixed the issue. Thanks.
