### ISSUE TITLE
Hint in user profile settings if plugin "Action Log - Joomla" disabled

### ISSUE THREAD

**Issue by ReLater** [joomla-projects/privacy-framework#124]
- Backend.
- Deactivate plugin "Action Log - Joomla"
- Go to your Super User profile > tabulator "Action Log - Joomla"

I think a hint concerning setting "Send notifications for User Actions Log" would be helpul like 
> Plugin "Action Log - Joomla" is disabled.

**Comment by mbabker** [comment]
👍 would definitely be a useful UX hint.  Or not adding the tab to the form at all if the logging isn't available.

**Comment by ReLater** [comment]
Let's say someone has already configured these options in the profile.
Then disables plugin "Action Log - Joomla" for some time.
Then saves the profile without this tab.

Should all settings of the tab then be lost or not? (I think, only if it's possible/feasible in some way, it would be nice to keep them untouched).

**Comment by alikon** [comment]
please test #236
