### ISSUE TITLE
Non-translated language strings in option=com_actionlogs&view=actionlogs

### ISSUE THREAD

**Issue by ReLater** [joomla-projects/privacy-framework#126]
### Steps to reproduce the issue
- Activate plugin "Action Log - Joomla"
- Do some actions like you can see on this image
![20-06-_2018_17-17-10](https://user-images.githubusercontent.com/20780646/41668040-bf799344-74ae-11e8-95dd-7f48b269cc10.png)
- Check that they are displayed correctly (like image above) in option=com_actionlogs&view=actionlogs

- Deactivate plugin "Action Log - Joomla".
- Check entries in option=com_actionlogs&view=actionlogs again
=> See next image
![20-06-_2018_17-21-40](https://user-images.githubusercontent.com/20780646/41668218-23650104-74af-11e8-8d78-c9f50b2d8028.png)

**Comment by ReLater** [comment]
Similiar issue with module "Latest Actions
![20-06-_2018_17-36-42](https://user-images.githubusercontent.com/20780646/41668877-a9bd21d6-74b0-11e8-863f-73ea3e84d40f.png)
"

**Comment by joomdonation** [comment]
I am not sure if this issue can be fixed. To have correct message displayed, we require the plugin language file loaded. However, in this case, you unpublished the plugin, the language file is not loaded and cause this issue.

**Comment by ReLater** [comment]
Even if it's a small overhead isn't it possible to load the language files of the plugin in the component, too.

I'm not shure if all of these extensions will become locked ones in core. But then all language files should be always present and loadable.

**Comment by brianteeman** [comment]
A logged extension could be uninstalled

**Comment by ReLater** [comment]
> A logged extension could be uninstalled

Yes, but the related actions and related message_language_keys (from plugin actionslog) are still present in table #__action_logs.

I'm just talking about language strings from plg_system_actionlogs here. If it will be a locked extension (I don't know) it should be possible to reliably load these language strings in component or module even if plugin is disabled. As a fallback.

**Comment by mbabker** [comment]
I don't see the issue with loading that plugin's language strings here.  It's a bit of an odd case because components shouldn't depend on a specific plugin, but this is a bit of a special exception (and affect languages versus code behavior, so not strictly the same argument).

**Comment by brianteeman** [comment]
@relater. Sorry I misunderstood which strings it was.

@mbabker should we be using strings from the component and not the plugin then?

**Comment by mbabker** [comment]
That'd probably be better.

**Comment by joomdonation** [comment]
We need to support third party plugins as well, so maybe we should still keep the language strings in the plugin itself.

So to solve this issue, we will need to load language files of all plugins from **actionlog** plugin group (both published and unpublished plugins). Guess that method should be added to component helper class so that it can be called easily in latest actions module?
