### ISSUE TITLE
Not all plugins' data added into exported xml

### ISSUE THREAD

**Issue by manojLondhe** [joomla-projects/privacy-framework#127]
### Steps to reproduce the issue

1. Install attached plugin and enable it
2. Create some articles, set user (eg user1) we want to export data for as author.
3. Send export request for this user (eg user1)
4. Goto backend, click on export button

### Expected result
- Data from user & content privacy plugins should be exported in xml

### Actual result

- Only data from user plugin is exported in xml
- Data from content plugin is exported in xml if we disable user plugin

### System information (as much as possible)

- php: Linux 4.13.0-45-generic # 50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64
- dbserver: mysql
- dbversion: 5.7.22-0ubuntu0.16.04.1
- dbcollation: utf8_general_ci
- dbconnectioncollation: utf8mb4_general_ci
- phpversion: 7.0.30-1+ubuntu16.04.1+deb.sury.org+1
- server: Apache/2.4.33 (Ubuntu)
- sapi_name: fpm-fcgi
- version: Joomla! 3.9.0-dev Development [ Amani ] 22-May-2018 14:00 GMT
- platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
- useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

### Additional comments

- If I add one more plugin and change ordering to have user plugin at the end, data of first 2 plugins is exported in xml.

[plg_privacy_content.zip](https://github.com/joomla-projects/privacy-framework/files/2122213/plg_privacy_content.zip)

**Comment by mbabker** [comment]
Fixed via bdc0282
