### ISSUE TITLE
Warnings and untranslated lang constant shown if onPrivacyCanRemoveData blocks deletion

### ISSUE THREAD

**Issue by manojLondhe** [joomla-projects/privacy-framework#129]
### Steps to reproduce the issue
1. Generate a delete account request for a super user (or generate it for a normal user and give him superadmin acess later)
2. Try deleting this user details from com_privacy

### Expected result
1. Translated strings for constants from related plugins should be shown (in this case Privacy - Users)
2. No warnings should be shown

### Actual result
1. Untranslated strings for constants from related plugins are shown (in this case Privacy - Users)
2. Warnings are shown

![privacy-delete-warning](https://user-images.githubusercontent.com/1375006/41708515-6b5d1f64-755e-11e8-8a38-75737c2bd895.png)

##### ( ! ) Warning: strpos() expects parameter 1 to be string, array given in ...privacy-fw-4/libraries/src/Language/Text.php on line 98
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1210	2811432	Joomla\CMS\Language\Text::passSprintf( )	.../Text.php:66
17	0.1210	2811432	strpos ( )	.../Text.php:98

##### ( ! ) Warning: explode() expects parameter 2 to be string, array given in ...privacy-fw-4/libraries/src/Language/Text.php on line 104
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1210	2811432	Joomla\CMS\Language\Text::passSprintf( )	.../Text.php:66
17	0.1214	2811432	explode ( )	.../Text.php:104

##### ( ! ) Warning: Invalid argument supplied for foreach() in ...privacy-fw-4/libraries/src/Language/Text.php on line 107
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1210	2811432	Joomla\CMS\Language\Text::passSprintf( )	.../Text.php:66

##### ( ! ) Warning: array_shift() expects parameter 1 to be array, null given in ...privacy-fw-4/libraries/src/Language/Text.php on line 112
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1210	2811432	Joomla\CMS\Language\Text::passSprintf( )	.../Text.php:66
17	0.1223	2827840	array_shift ( )	.../Text.php:112

##### ( ! ) Warning: strtoupper() expects parameter 1 to be string, array given in ...privacy-fw-4/libraries/src/Language/Language.php on line 314
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1230	2827816	Joomla\CMS\Language\Language->_( )	.../Text.php:80
17	0.1230	2827816	strtoupper ( )	.../Language.php:314

##### ( ! ) Warning: strpos() expects parameter 1 to be string, array given in ...privacy-fw-4/libraries/src/Language/Language.php on line 358
Call Stack
No.	Time	Memory	Function	Location
1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1210	2811408	Joomla\CMS\Language\Text::_( )	.../actionlogs.php:148
16	0.1230	2827816	Joomla\CMS\Language\Language->_( )	.../Text.php:80
17	0.1236	2844200	strpos ( )	.../Language.php:358

##### ( ! ) Notice: Array to string conversion in ...privacy-fw-4/administrator/components/com_actionlogs/helpers/actionlogs.php on line 148
Call Stack
No.	Time	Memory	Function	Location

1	0.0001	372968	{main}( )	.../index.php:0
2	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->execute( )	.../index.php:51
3	0.0196	1438912	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:195
4	0.0504	2273688	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:159
5	0.0984	2317272	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:101
6	0.0994	2346480	Joomla\CMS\Component\ComponentHelper::executeComponent( )	.../ComponentHelper.php:357
7	0.0994	2363328	require_once( '...privacy-fw-4/administrator/components/com_privacy/privacy.php' )	.../ComponentHelper.php:382
8	0.1010	2443776	PrivacyController->execute( )	.../privacy.php:19
9	0.1010	2443776	PrivacyController->display( )	.../BaseController.php:710
10	0.1077	2491384	PrivacyViewRequest->display( )	.../controller.php:91
11	0.1148	2662416	PrivacyViewRequest->display( )	.../view.html.php:96
12	0.1148	2662416	PrivacyViewRequest->loadTemplate( )	.../HtmlView.php:230
13	0.1149	2680008	include( '...privacy-fw-4/administrator/components/com_privacy/views/request/tmpl/default.php' )	.../HtmlView.php:697
14	0.1209	2809736	ActionlogsHelper::getHumanReadableLogMessage( )	.../default.php:81
15	0.1239	2844552	str_replace ( )	.../actionlogs.php:148

**Comment by mbabker** [comment]
Fixed the missing language constant with cedca97d58385f1f90f7956f84a8baa1e6b36d1a

Fixed the warnings with e7ab13b4c9d3ef12960782a652c2a190454a5c01
