### ISSUE TITLE
config params for plugins of privacy group

### ISSUE THREAD

**Issue by FoTo50** [joomla-projects/privacy-framework#134]
Not sure if this is a bug or maybe there is a still undocumented different way for this:

I created a plugin for J3.9 in group privacy to trigger onPrivacyExportRequest and onPrivacyRemoveData similar to PlgPrivacyUser for adding extension specific data to export and/or remove it, but in my case with some config params in the manifest xml (as usual) to let webmasters choose, what should take affect.

The fields turn up fine, but unfortunately these params do not get saved when editing the plugin settings.

Greetz

**Comment by mbabker** [comment]
Plugin params are plugin params and always managed through `com_plugins`, we haven't changed anything about that.

**Comment by FoTo50** [comment]
My mistake, sorry ... but post the reason here in case someone catching it via google ;)

I just wrote `<fields>` instead of `<fields name="params">` in manifest file

Grrr, sometimes u look hundret times on a line and dont see the error ... ;)

Greetz

**Comment by mbabker** [comment]
It happens to all of us!
