### ISSUE TITLE
Administrator User cannot access privacy menu

### ISSUE THREAD

**Issue by webgras** [joomla-projects/privacy-framework#137]
### Steps to reproduce the issue
Create new user with administrator rights.
Login to backend
Open menu "users" click on "Privacy" or "User Actions Log"

### Expected result
Privacy or Actions Log is opening

### Actual result
An error has occurred.
403 You are not authorised to view this resource.

### System information (as much as possible)
PHP Built On | Linux  #199-Ubuntu SMP Thu May 17 10:12:50 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.6.38-nmm1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.11-nmm1
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.0-dev Development [ Amani ] 26-June-2018 15:45 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

### Additional comments
I think, that if I see the menu items, then I should have the rights to see the according content as well. Otherwise, we need to hide the menu items. But as an administrator I am able to configure plugins, so I should be able to see action logs and privacy stuff. However, I don't know if you have discussed this already.

**Comment by webgras** [comment]
![admin-menu](https://user-images.githubusercontent.com/10774704/42032946-8270dd3a-7adb-11e8-9ae8-6d465446be85.png)
Also in the control panel, the "Maintenance" module is not showing the content. But I guess this is connected with the menu items --> either we should hide the module or change the rights.

BTW: really great work done!!! Thanks a lot!!!

**Comment by mbabker** [comment]
> But as an administrator I am able to configure plugins, so I should be able to see action logs and privacy stuff. However, I don't know if you have discussed this already.

It's an explicit decision these components are only accessible to super users due to their nature.

**Comment by webgras** [comment]
ok.
but shouldn't we hide them in the menu for administrators?

**Comment by mbabker** [comment]
Menu item hidden for com_privacy.

@alikon or @joomdonation can one of you look at the ACL stuff for the action logs component?  The front file checks `core.manage` permission, then the controller checks for `core.viewlogs`.  This really should be consistent and if we need a special case in the menu module then add it.

**Comment by brianteeman** [comment]
for com_installer, which also is restricted to super users, we do have a full acl configuration available

**Comment by mbabker** [comment]
ACL checks should all be resolved now.
