### ISSUE TITLE
Permission tab missing in options "Privacy"

### ISSUE THREAD

**Issue by webgras** [joomla-projects/privacy-framework#138]
### Steps to reproduce the issue
Login to backend as super user
go to "Users" - "Privacy"
click "Options"

### Expected result
see "Permissions" beside "Options"

### Actual result
only tab "Options"

### System information (as much as possible)
Joomla! 3.9.0-dev Development [ Amani ] 26-June-2018 15:45 GMT

### Additional comments
![permissions](https://user-images.githubusercontent.com/10774704/42033277-b0f1dad2-7adc-11e8-8464-bb9789564892.png)

**Comment by mbabker** [comment]
Expected behavior.  There is no ACL to configure for the component.  Either you're a super user and have access or you're not and you don't.
