### ISSUE TITLE
Missing string?

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/privacy-framework#144]
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_IN

**Comment by joomdonation** [comment]
It's here https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini#L35

**Comment by infograf768** [comment]
Yes, just saw it as well as LOGGED_OUT
But it it is not always translated in the mails I receive.
```
Action | Date | Extension | Name | IP Address
-- | -- | -- | -- | --
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_OUT | 2018-06-29 07:29:34 | Users | Super User | 1
```
```

Action | Date | Extension | Name | IP Address
-- | -- | -- | -- | --
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_IN | 2018-06-29 07:20:50 | Utilisateurs | Super User | 1

```

**Comment by joomdonation** [comment]
Maybe the language file is not loaded somehow. Does it always happen?

**Comment by infograf768** [comment]
Looks like I can solve it by adding in `/administrator/components/com_actionlogs/models/actionlog.php
```
$lang   = JFactory::getLanguage();
$lang->load(strtolower('PLG_ACTIONLOG_JOOMLA'), JPATH_ADMINISTRATOR, null, false, true)
			|| $lang->load(strtolower('PLG_ACTIONLOG_JOOMLA'), $source, null, false, true);
```

**Comment by joomdonation** [comment]
We should find root reason of the error. Keep in mind that can have additional log plugins added by third party extensions, too. So we need to find out why language file is not loaded and address it properly

**Comment by infograf768** [comment]
Agree.

**Comment by brianteeman** [comment]
No band aid solutions please

**Comment by infograf768** [comment]
> No band aid solutions please

Who said we would use bandaids? My comment was evidently just to show that there was an issue concerning lang files loading there. And, to test, I forced loaded the file...

**Comment by joomdonation** [comment]
In theory, the language file of that plugin should already be loaded, so we should not have to add extra code for this. 

I will try to test it myself to see why it happens when I get home later today

**Comment by infograf768** [comment]
Ok, this may be due to this code.
https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/administrator/components/com_actionlogs/helpers/actionlogs.php#L252-L256

When commenting it, I have no more problems
```
			// If language already loaded, don't load it again.
			//if ($lang->getPaths($extension))
			//{
			//	continue;
			//}
```
@mbabker  Quid?

**Comment by mbabker** [comment]
It's in essence the same logic as the plugin [loadLanguage](https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/libraries/src/Plugin/CMSPlugin.php#L130) method, so that shouldn't be it in theory.

**Comment by joomdonation** [comment]
I could not re-procedure the issue myself, so I could not check it :(. Maybe someone else can try?

**Comment by infograf768** [comment]
php 7.1.13, sql 5.6.35 (if it helps)

**Comment by infograf768** [comment]
Now it works, weird...
Closing for now. Will check again another day.
