### ISSUE TITLE
Actionlogs need to have a privacy plugin

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#160]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402752901

Stupid question, but: Don't we have to include the content of the specific user of the actionlog in the export, too? And if there is no data for a domain in the export (no user notes for example) shouldn't that whole domain be left out?

Related:
* https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402967964
* https://github.com/joomla/joomla-cms/pull/20800#issuecomment-403013037

**Comment by alikon** [comment]
No for me,  i don't consider actionlogs as user data

**Comment by Hackwar** [comment]
Closing since we have a PR #202
