### ISSUE TITLE
Wrong subject for deletion request email

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#162]
From this comment by @jeckodevelopment https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402981781

While submitting a Deletion Request the email received by the user has the following subject:

Information Request Created at [Sitename]

For clarity it can be changed to "Information Deletion Request" in case of deletion, giving that the current subject is instead perfect for Information Requests.

**Comment by alikon** [comment]
make sense to me

**Comment by joomdonation** [comment]
I think it can be done by allow using different email subject base on the request type (same as email body) https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/components/com_privacy/models/request.php#L146

So it is needed, we can make an easy PR.

**Comment by alikon** [comment]
see #179

**Comment by alikon** [comment]
solved by #179

**Comment by jeckodevelopment** [comment]
Thank you :)
