### ISSUE TITLE
com_messages needs a privacy plugin

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#165]
From this comment by @mbabker and me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402880750

> Don't we have to include the content of the specific user of the actionlog in the export, too?

Thinking back on it, we probably need to add plugins for:

* Messaging (this one gets kind of interesting because through the UI you can't read someone's messaging threads (in the database you can) but the export would expose those to a super user)

For categories and tags, I would suggest these are NOT the user's data for export as it relates to the site's content hierarchy (it would be kind of like including menu items simply because you were the one who created them if we tracked that data). That doesn't stop anyone from writing plugins to include it but from a core perspective I think we don't need to worry about it.

**Comment by alikon** [comment]
see #187

**Comment by alikon** [comment]
please test #187
