### ISSUE TITLE
Log consent to terms & conditions

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#166]
From this comment by me and @brianteeman https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402661866

> > Consent to terms&conditions is not stored

> This is a privacy tool - we only need to log consent to privacy

Then add this as a separate logging event into the actionslog. With this checkbox being a new feature and thus existing users being forced to consent to it now, the date of registration and consent could be different.

**Comment by brianteeman** [comment]
I stand by my previous resonse.

> Not really a new feature. Just extracted the one from the user profile plugin so you can use just this one field without needing all the others. Unlike the privacy plugin which when applied forces all existing users to consent on login this tos plugin does not force anything on existing users.

**Comment by mbabker** [comment]
Putting it in the action logs is enough.  It's not really something from our design perspective needs to be logged to the privacy consents system as terms & conditions are a separate thing from privacy policies and whatnot, therefore I don't think we really need to "permanently" retain this consent either.  This one's really more of a user convenience than a hard "you must agree to this or you can't do anything" type of deal (and of course nothing stops the site owner from shutting down the account if they don't agree).

**Comment by Hackwar** [comment]
If we log the consent to the privacy terms, then it sounds just logical to me to log the consent to the t&c. I just noticed this and didn't want us to miss something here. If you decide against this, we can close this one, otherwise we need to add the logging here quickly. :smile:

**Comment by brianteeman** [comment]
The intent of this pr is to satisfy various legal requirements about consent.

**Comment by mbabker** [comment]
If someone does want to log it it's not difficult to do, beyond that I don't think we really NEED to add it here.

**Comment by Hackwar** [comment]
I proposed it, I would implement it, but I wont decide if we implement this. I would need your decision on this. Simply close it if we don't want it or give me the go.

**Comment by alikon** [comment]
personally speaking it doesn't hurt if we store this info to the log

**Comment by Hackwar** [comment]
PR #220 implements this, so I'm closing this one.
