### ISSUE TITLE
com_actionlogs: improve export filename

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#172]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402661866

The filename of the CSV export has UTC time, which I can understand why, but then we should add UTC in front of it.

**Comment by brianteeman** [comment]
Feel free to submit a pr to do that - can't see the need myself but if you want to then go for it

**Comment by joomdonation** [comment]
I don't see the need myself, too. However, If I were modified it, I would use current user timezone because it's easier for him to see when the it was exported by looking at filename

**Comment by Hackwar** [comment]
I thought the user timezone might be good, too, but then I thought about inter-timezone disputes. If we have an admin and a disputee with differing timezones, then storing the file with the timezone of one of the two might create more confusion, so I would just try to make clear that the timestamp in the filename is in UTC.

**Comment by Hackwar** [comment]
I added "UTC" to the filename in #197. What do you think about this? If I get more than one downvote, I'll simply close PR and issue. Don't need to waste more time on this than absolutely necessary. :wink:

**Comment by alikon** [comment]
not a downvote from my but imo not so a priority ...

**Comment by Hackwar** [comment]
To cleanup, I'm closing this issue. The PR is where we should discuss this further and decide.
