### ISSUE TITLE
com_actionlogs: Edits to global configuration are not logged

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#173]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402661866

Edits to Global Configuration are not logged

**Comment by joomdonation** [comment]
If I understand your issue correctly, it should be sorted by PR https://github.com/joomla-projects/privacy-framework/pull/146

**Comment by Hackwar** [comment]
I don't think so. I'm talking about the site configuration in com_config. In my tests, changes to a components configuration was correctly saved in the log, but changes to configuration.php through the GUI was not.

**Comment by joomdonation** [comment]
Ah, I mis-understood the issue

**Comment by joomdonation** [comment]
So I tried and it's working OK to me. 

1. Access to System -> Global Configuration

2. Select User Actions 

3. Tried to change the parameters, it's being saved properly

So I'm not sure what's wrong here?

**Comment by mbabker** [comment]
The actual global configuration.  Not "go to global configuration then choose a component to change a component's configuration".

**Comment by Hackwar** [comment]
We have a PR #200
