### ISSUE TITLE
Codereview for com_privacy language file

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#175]
From this comment by me and @neo191987 https://github.com/joomla/joomla-cms/pull/20800#discussion_r200202881

Again, please refer to the linked comment

**Comment by joomdonation** [comment]
Only language items belong to language file of:

-com_actionlogs
- system action log plugin
- one of the action log plugin

will be used to to translate and make the action log readable. So in this case, we will have to move these language items to com_actionlogs language file or system action log plugin to have it translated properly

**Comment by alikon** [comment]
if we need to move these string i'd prefer to move on com_actionlogs

**Comment by Hackwar** [comment]
We have a PR to fix the issue from @neo191987 #221. Closing this one.
