### ISSUE TITLE
Codereview com_privacy SQL

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#176]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#discussion_r199325798

Should we add an IP column to #__privacy_requests?

**Comment by alikon** [comment]
yes we can... :smiley: 
but  what should be the + value and how we should manage this data ?

**Comment by Hackwar** [comment]
Thinking about this some more, I think we can drop this. We are logging the request to com_privacy in the user actionlog and thus we should have that data already in the system. So this would just be duplication.

**Comment by mbabker** [comment]
Another thing to consider is the IP will be whomever initiates the request, be it admin created or frontend form.  In the case of an admin creation, (hopefully) all it says is what computer I was logged in to when I added your request.
