### ISSUE TITLE
Codereview com_actionlogs helper

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#177]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#discussion_r199324065

The getDataByPks() method is such a general method, that it feels wrong here.

**Comment by Hackwar** [comment]
Also from this comment https://github.com/joomla/joomla-cms/pull/20800#discussion_r199324036
And https://github.com/joomla/joomla-cms/pull/20800#discussion_r199323965
The comments are strange

**Comment by alikon** [comment]
if i'm understood well  it's only a naming convention issue so what it should be  ?
`getDataByActions` ?
consider we are only calling in this way `ActionlogsHelper::getDataByPks` 
https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/plugins/actionlog/joomla/joomla.php#L275

**Comment by joomdonation** [comment]
Actually, the method is only used to get title of published/unpublished items (categories, articles...) and add that title to each action log record (getting $pk from the method can be removed as it's not used at the moment)

How about rename it to **getItemsTitle** ?

**Comment by Hackwar** [comment]
That method is retrieving an arbitrary field with the corresponding ID from an arbitrary table. You could name this Database::loadValueFromTable() and it would be fine, but here this is such a general method, that I think it is wrong here. What is keeping you from retrieving the title of an article with this? Or the parameters of a contact? This is simply not com_actionlogs specific code, but something that I would (in worst case) expect as part of an ORM or database library.

**Comment by Hackwar** [comment]
Closing in favour of #226.
