### ISSUE TITLE
Privacy terms are not linked in Privacy Consent Plugin

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#178]
From this comment by @b10tds https://github.com/joomla/joomla-cms/pull/20800#issuecomment-403103250

Just upgraded my dev system to it, first thing I would say is there is a reference at the bottom of the initial privacy form that appears when you confirm agreement to a privacy policy, but there is no policy (Yes I appreciate I will have to create one) or link to any policy. May I suggest that a "raw default policy" is included, that can be updated/edited by the admin, and is linked to prior to the user having to click the agreement policy button.

**Comment by brianteeman** [comment]
We absolutely can not nor should we ever put content on a site. Especially when it has legal consequences

**Comment by alikon** [comment]
fully agree

**Comment by brianteeman** [comment]
It can also be compared to the contact component. Joomla provides the form but it is the site builders job to add the email address.

**Comment by b10tds** [comment]
I think you are missing the point, the page clearly states to accept the privacy policy you click the button, but there is no link to ANYTHING! My suggest re a raw privacy policg document is a bkank one for example with say “Enter you privacy policy details here”, with say a link in it, only available to a superuser. No legal implications about this at all!

**Comment by Hackwar** [comment]
Of course we can't provide a privacy policy, but in the form field in the text we have to add a link to the privacy policy that is set in the plugin if there is no text in the short description field.

**Comment by b10tds** [comment]
I give up, if you can’t bother to read what I write I shan’t bother again.  Not a way to get future feedback from users at all.

**Comment by mbabker** [comment]
What is it you're trying to suggest?  Because reading your comment 3 times over I too am getting the impression you're asking for us to ship a default privacy policy article, which I agree is not something we should be doing.

Even having an empty article in the core data set just doesn't seem like a good idea to me either.  If we were going to go this route, I would really just say stop using com_content for the policy and kind of emulate how WordPress steers people to creating a policy page (which we can better do if the policy is managed in the privacy component versus trying to do some crazy integration in com_content, I just also dislike the thought of duplicating a lot of com_content logic for a single item).

**Comment by alikon** [comment]
maybe I've just not fully understand what you mean, please be so kindly and give us the chance to understand you :smile_cat:

**Comment by b10tds** [comment]
Read my posts again, they are quite clear. You have released this for testing, I instalked it on my dev system. I treat my testing as an uninformed and unskilled user, which an awful lot are. 
When I first loaded the dev system home page, it immediately displayed the new privacy plugin generated page. This page makes reference to accepting the privacy policy which as I understand tge system logs against the user account. There is nothing to identify the “privacy policy” to the user, superuser in this instance, and once you clip the accot button there is no way back. You are going to have a lot of cery confused unskilled admin users that have no idea what to do, how to create or even check the policy once they have been guided to the plugin.
My suggestion, as I already clearly stared, is that, for the superuser only, there should either be a link to a dummy policy document, with just tgat states in it, with a link to edit the “policy” document. No legal issues here what so ever if you follow my suggestion. I would also provide a mechanism that allows the superuser to revusit the page/form that a normal user would see, at any time, so tgey can view what a normal user would be presented with. I trust this is clear enough this time. And just for your information I implemented action logs in my system nearly 10 years ago, that users have available to then to view only.

**Comment by brianteeman** [comment]
> When I first loaded the dev system home page, it immediately displayed the new privacy plugin generated page. 

It can only do that when you log in on the front end

**Comment by b10tds** [comment]
Not correct, if you still have an active session it will display as soon as you load the site. When site admins update an existing site most of them will probabky already have an active session!
Not after an argument here but I think your current implimentations workflow will cause a lot of headaches fir, and, disgruntled site admins. 
I have tried to help, I can do no more.

**Comment by Hackwar** [comment]
Enable the ```Privacy Consent System``` Plugin, set an article for the privacy policy and go to the registration form. You have the checkbox to consent to the privacy policy, but no link to that policy.

At that point: Are we logging the specific version of a document that the user agreed to? And do we have a feature to reset the consent to request the user to agree again when the privacy policy has changed?

**Comment by b10tds** [comment]
You beat me to it Hannes. My thoughts were the same, but typing on a mobile is getting tedious and trying, for me!

**Comment by Hackwar** [comment]
Don't worry. Just relax a bit. Nobody is trying to insult anyone.

**Comment by b10tds** [comment]
I’m very relaxed, you will have no doubt when I’m not 😄

**Comment by brianteeman** [comment]
Found the problem!!!!

The plugins are enabled by default - they absolutely should not be

**Comment by brianteeman** [comment]
This is a clean install of the special pack @mbabker  made for testing

<img width="447" alt="chrome_2018-07-06_21-48-08" src="https://user-images.githubusercontent.com/1296369/42399589-4d876454-8166-11e8-9e18-c54a9c717075.png">

**Comment by brianteeman** [comment]
the only one of those plugins that should be possibly enabled by default is system log rotation

**Comment by mbabker** [comment]
The privacy and quick icon plugins are safe too.  But the plugins adding consents definitely should default disabled.

**Comment by brianteeman** [comment]
Resolve that and the reported issue goes away. No need to have a dummy article as it is clear to the site admin when they set it up what to do. No surprises being forced to consent to something that doesn't exist etc.

**Comment by Hackwar** [comment]
So we are not

**Comment by Hackwar** [comment]
So we are not going to add a link to the article that the admin selected in the default string in the short description?

**Comment by brianteeman** [comment]
Not sure I understand you @Hackwar 

We have a field where you can either use the default message (useful if its a multilingual site) or write your own message AND a link to an article which can be associated in many languages. You do not have to have an article - you might be happy with just the short message.
https://docs.joomla.org/J3.x:Privacy

**Comment by Hackwar** [comment]
I understand that, but my expectation would be, that a link to the privacy policy appears the moment that I select an article in the plugin.

**Comment by brianteeman** [comment]
it does

**Comment by Hackwar** [comment]
Ok, not directly obvious to me, but then this can be closed.
