### ISSUE TITLE
Username is not ananonymisied in com_actionlogs

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/privacy-framework#186]
### Steps to reproduce the issue

- Register as user
- confirm etc
- edit the user as admin
- the new user requests to be deleted
- user get ananonymisied

### Expected result

the name of the user is gone in com_actions logs too.

### Actual result

![image](https://user-images.githubusercontent.com/2596554/42414778-765352a8-823d-11e8-9e97-83d329fd4e8b.png)

**Comment by brianteeman** [comment]
I would say that is correct. Just because you ask to be removed from a site doesn't mean that everything will be removed. I would want to keep a log of who did what and when. I might even need to keep that for legal reasons.

**Comment by zero-24** [comment]
Thanks

**Comment by zero-24** [comment]
Just for the reccord `Tobias` and `Tobias Zulauf` are different users. The first on the SU and the other one is the registered user. Just noticed that but when we need to keep them for legal i'm out :)
