### ISSUE TITLE
Show User ID in consents

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/privacy-framework#190]
<img width="1432" alt="grafik" src="https://user-images.githubusercontent.com/828371/42422831-8b4b3322-82ee-11e8-9ff9-86657b51243a.png">

I think the User ID should be shown in this overview for a more unique identification...

**Comment by brianteeman** [comment]
afaik username is a unique field

**Comment by coolcat-creations** [comment]
But the Username can change, It will be changed here too but a userid will always stay the same...

**Comment by mbabker** [comment]
The user ID is stored in the database, the username is queried when the consents view is loaded so the name shows up instead of the user ID.  Same as most any place else where we show the user's name or username in the UI.

**Comment by jeckodevelopment** [comment]
username is more user friendly to see instead of ID.
You're right to say that username can change, but i guess that in large websites it's too difficult at a glance to immediately connect the request to the user only viewing the ID.

**Comment by coolcat-creations** [comment]
Yes, I meant it as an additional information, not instead of the username. It is depending of course of everyones own workflow but when I collaborate on websites with the customer or others I often say: look /search for the user with the ID 12345 or the article with the id 676 instead of spelling the name of the item at the phone.
How would you search for the username єℓɪsαsσρɢυα when you don't have that string somewhere to copy from?

**Comment by brianteeman** [comment]
although I always use the title and not the id I can see the use case with non native language names. Its easy enough to add an ID column and we should do it

**Comment by brianteeman** [comment]
I will work on it this morning

**Comment by brianteeman** [comment]
Closed see #195
