### ISSUE TITLE
Privacy Policy Subform for Multilanguage

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/privacy-framework#191]
<img width="1084" alt="grafik" src="https://user-images.githubusercontent.com/828371/42422872-65b60960-82ef-11e8-9f02-215c60066f72.png">
Should there be an option to select the privacy policy for other languages?

**Comment by mbabker** [comment]
It uses the existing associations system (since in theory your privacy policy article should be associated with the same article in all languages).

**Comment by brianteeman** [comment]
exactly the same as the tos field in the userprofile plugin

**Comment by infograf768** [comment]
Indeed. I already tested that and it works fine.
