### ISSUE TITLE
Privacy Policy Message in Register Form

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/privacy-framework#192]
<img width="688" alt="grafik" src="https://user-images.githubusercontent.com/828371/42422910-20dd603a-82f0-11e8-83c7-2bbf561f5cd0.png">

Would be great to be able to use JTEXT here for other languages.

**Comment by brianteeman** [comment]
would be great but not possible. It's an issue with joomla and how the field was coded originally see #12793

**Comment by coolcat-creations** [comment]
but how can one insert here text in the sitelanguage? If you refer to https://github.com/joomla/joomla-cms/issues/12793 thats not the default value i am speaking about. I put in a PRIVACY_MY_TEXT string and added it into the overrides but it's not translated.

**Comment by coolcat-creations** [comment]
I see, so it IS translateable but was coded that way that I can't use an own string. I think It should be easy to use an own string, because it's not about #12793 - you can just wrap a JTEXT around the output and it will be translated if an override is available.

**Comment by brianteeman** [comment]
as explained on your pr that doesnt work

**Comment by coolcat-creations** [comment]
How did you test this for me it did work ?

**Comment by brianteeman** [comment]
yes sorry I was getting confused with #12793 That "bug" was the reason that its a hint and not a default value.
