### ISSUE TITLE
How can an extension add new data to #__action_logs_tables_data

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#199]
I could only find one place in the code where #__action_logs_tables_data is accessed. How can an extension add itself to this table? Preferably not by writing its own SQL or even calling an API. I would expect that you could simply add this info to your manifest and that it adds/updates the data automatically... Adding this in a required install script raises the bar significantly.

**Comment by alikon** [comment]
this was one of the thing that wasn't  covered from gsoc16, but i really think that is a plus feature, so pr's are wellcome

**Comment by mbabker** [comment]
It'd be a SQL statement for now, same as you have to do if you're supporting tags/versioning with the UCM and content types stuff.  Since we don't have a nice way for components to hook the install process to support opt-in tags, it's either SQL statements or make library APIs for component specific features.

**Comment by Hackwar** [comment]
I think this is something that we should handle in a later release. I have several possible ways to solve this, none of which seem like the ideal solution. So I will open a new issue in the Joomla tracker and then we should tackle that there when we have time. :see_no_evil:

**Comment by mbabker** [comment]
> we should tackle that there when we have time. 🙈

Hopefully someone has a [rainy day](https://github.com/joomla/joomla-cms/blob/d18979642bd5d13ae68bbdf09b6d5b484cb32f6b/plugins/user/joomla/joomla.php#L109) to actually do that 🤣
