### ISSUE TITLE
Privacy Policy Acceptance

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#2]
Using https://github.com/joomla/joomla-cms/pull/20051 as a foundation, the privacy system should make it easy to track user agreements related to this policy.

This should also take into consideration how changes in a site's policy need to be handled (email notification, require re-acceptance, etc.).

**Comment by JoomliC** [comment]
I've read this here : https://techblog.bozho.net/gdpr-practical-guide-developers/

> Re-request consent – if the consent users have given was not clear (e.g. if they simply agreed to terms & conditions), you’d have to re-obtain that consent. So prepare a functionality for mass-emailing your users to ask them to go to their profile page and check all the checkboxes for the personal data processing activities that you have.

It could be a bit weird...

**Comment by JoomliC** [comment]
What the news about this ?

As you said @mbabker, the work done by @brianteeman is already a good foundation.

**Comment by mbabker** [comment]
Still needs to be worked on.  I've been doing other stuff in `com_privacy` and dealing with the release, so personally I haven't had time to work on other stuff.  And Brian's noted his time is maxed out for now.  If someone wants to pick up on it though it'd be helpful!

**Comment by joomdonation** [comment]
Do we have list of issues/tasks from @brianteeman PR need to be addressed? If Yes, how should we process to get it done? If the tasks are clear, I can give it a try.

**Comment by joomdonation** [comment]
So how should we process with it? Assume I come up with the code, should you open a PR on this repo or re-open your PR in the the cms repo?

**Comment by brianteeman** [comment]
ok let me open that branch as a pr here and then you can work with that

**Comment by joomdonation** [comment]
OK. We will get it done

**Comment by brianteeman** [comment]
#48

**Comment by JoomliC** [comment]
👍 

> The main (only) issue is that when an existing user is redirected to the confirmation page they should not be able to do anything else until they have confirmed.
If you look at the way the password reset required works then you will see what needs to be done

Great idea to use framework for this as for Required password reset!
This could allow too to add this in batch and in user options (this may handle changes in a site's policy).
Consent could work the same!

About storing of consents, i think it could be in a specific view of com_privacy, instead of notes.

**Comment by brianteeman** [comment]
When I wrote it com_privacy didnt exist ;)

**Comment by JoomliC** [comment]
> When I wrote it com_privacy didnt exist ;)

Yes i know ;-)
This is more a question to validate the way to finalize your good work!

As for me, only this 2 points to do!

**Comment by mbabker** [comment]
Covered by #49
