### ISSUE TITLE
[RFC] Move user log notification settings to own table.

### ISSUE THREAD

**Issue by SharkyKZ** [joomla-projects/privacy-framework#201]
`com_actionlogs` introduces a bad practice of running text search against JSON encoded params column:
https://github.com/joomla-projects/privacy-framework/blob/ad6e4d293f3f5c51e742a18feff3ab5130b4f0b6/administrator/components/com_actionlogs/models/actionlog.php#L103-L105
This is volatile and could get really slow on larger sites. Propose to move these settings to a separate table and handle data saving by plugin. I.e. same way `User - Profile` plugin does.

**Comment by SharkyKZ** [comment]
The format doesn't have to be like in profile plugin. I meant it as an example for saving data through user events. We could avoid using EAV here. Searchable params could have their separate columns while non-searchable params would be encoded in single column (these could actually stay in `#__users` table but that could be confusing).

A table with just user ID, logs_notification_option and params columns would suffice at the moment. And the query would look like this:
```
SELECT `a`.`email`,`b`.`params` FROM `#__users` AS `a` INNER JOIN `#__action_logs_notification` AS `b` ON (`b`.`logs_notification_option` = 1 AND `a`.`id` = `b`.`user_id`)
```

**Comment by alikon** [comment]
`logs_notification_option` for me can be an attribute (ie a new field) of the `#__users` table

**Comment by mbabker** [comment]
... except that then couples `com_actionlogs` data with `com_users`, unless this log notification stuff is going to be used for more than the single component that shouldn't happen.

**Comment by SharkyKZ** [comment]
Moving discussion to https://github.com/joomla/joomla-cms/pull/21983
