### ISSUE TITLE
Move Users request under "Users" section

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla-projects/privacy-framework#203]
### Is your feature request related to a problem? Please describe.
Currently the Users Request related to Privacy is under the Maintenance section in the Admin Cpanel:
![immagine](https://user-images.githubusercontent.com/733133/42624560-ea0c0812-85c5-11e8-82d2-2e513c48c81f.png)

### Describe the solution you'd like
I'd suggest to move it under the Users Section since it's related to users.

![immagine](https://user-images.githubusercontent.com/733133/42624594-009fbfba-85c6-11e8-9d63-127a298c104c.png)

**Comment by mbabker** [comment]
That's fair, implemented.

**Comment by jeckodevelopment** [comment]
Thank you
