### ISSUE TITLE
Badge "info" on Active Request = 0

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla-projects/privacy-framework#205]
### What needs to be fixed
Badge should be "info" instead of "warning" when the number of active requests is **0**.
It should be "warning" when the number of active request is greater than 0.

### Actual result
![immagine](https://user-images.githubusercontent.com/733133/42682278-67b6f564-868a-11e8-9b4d-52ac13b7d66d.png)

### Expected result
![immagine](https://user-images.githubusercontent.com/733133/42682318-80ca9010-868a-11e8-93c1-ab59293af5f6.png)

**Comment by Hackwar** [comment]
Please close this issue, since we have a PR: #216
