### ISSUE TITLE
[RFC] "Extension" column to Consents

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla-projects/privacy-framework#206]
### Describe the solution you'd like
Thinking about APIs, should we add the column "Extension" in the Consents page?
![immagine](https://user-images.githubusercontent.com/733133/42682569-40c6c424-868b-11e8-9657-c0d4eef9dc7b.png)

To have something like:

| Username | User ID | Extension | Subject | Body | Created | ID |
|---	|---	|---	|---	|---	|---	|---	|
| name | XX | Core | Privacy Policy | Description 	| xx minutes ago | YY |
| name | ZZ | Newsletter Extension Name | Subscription | Description | xx minutes ago | WW |
| name | QQ | Forum Extension Name | Registration | Description | xx minutes ago | RR |

In this way we can provide a centralized place for all the consents of the website.

**Comment by Hackwar** [comment]
Lets add a context column to the DB, similar to the extension column of #__categories with a similar functionality. I'll see if I can create such a PR this evening.

**Comment by Hackwar** [comment]
I've reviewed this again and I think we don't need the extension column. In #224 I changed the subject field to store a translateable string and we can simply filter by that. So with that change, I would close this issue.

**Comment by jeckodevelopment** [comment]
Thanks @Hackwar
