### ISSUE TITLE
Missing consent "evidence" on contact form

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla-projects/privacy-framework#213]
Currently, when an user submits a request through the Contact Form he/she's prompted to grant a consent to process the request thanks to the new plugin, so the user has to flag the checkbox to proceed. And that's ok, but site owner must be able to demonstrate that the user gave his/her consent to process the request/data. 

### Describe the solution you'd like
We could have two opportunities:

1. Add a copy of the consent statement in the email that is sent through the Contact Form.
2. Record the consent in the Consent view within Privacy Dashboard (index.php?option=com_privacy&view=consents)

**Comment by brianteeman** [comment]
the fact that it is a required field is the evidence that the person consented.

recording the consent in the privacy dashboard is pointless as this contact form can be submitted by guest users

**Comment by jeckodevelopment** [comment]
> recording the consent in the privacy dashboard is pointless as this contact form can be submitted by guest users

That is true.

> the fact that it is a required field is the evidence that the person consented.

That would not so easy to bring as argument. It would be much better to have the statement in the email that is sent after form submission.

**Comment by brianteeman** [comment]
do you require and record a consent before someone sends you an email?

**Comment by jeckodevelopment** [comment]
Nope. But, if someone sends me a message through the website, i need to demonstrate that the user read and accepted the privacy policy shown on the website.

**Comment by Sandra97** [comment]
And com_contact doesn't store information in the DB, so I don't think it's needed to keep track of their consent in the DB (and then in that case you are finally storing their data)

**Comment by jeckodevelopment** [comment]
> And com_contact doesn't store information in the DB, so I don't think it's needed to keep track of their consent in the DB (and then in that case you are finally storing their data)

That's why having a "confirmation text" in the email would be the perfect way to achieve it.

**Comment by mbabker** [comment]
There is no hook system to alter emails, so without hardcoding things into com_contact, we can't change any email contents.

**Comment by jeckodevelopment** [comment]
> There is no hook system to alter emails, so without hardcoding things into com_contact, we can't change any email contents.

In this case i believe that hardcoding something like the following sentence is not so bad:

 `The user accepted the privacy policy to process this request on DATE`

**Comment by mbabker** [comment]
Not really.  It would only be true if the plugin asking consent is enabled and all the pre-conditions involving that has been set.  Even then, that means hardcoding a plugin's configuration into a component, which is not proper system design (a component should not be aware of a specific plugin's presence at all).

**Comment by brianteeman** [comment]
You can't hard code it into the email because not all sites will require the consent

**Comment by Hackwar** [comment]
I would see the situation in the following way: The spirit of GDPR is to make it obvious to the user what data a website collects about a person. In the case of a contact form, all data is provided by the user. So the consent of the user is given the moment that he typed it into the form. It is also not required that the user typed in real data. Long story short: For now I would say that the implicit consent was given when the contact form was filled out and the explicit consent was given when the checkbox was checked. That explicit consent is implicitly stored by the timestamp of the send mail.

So I would vote against coding anything into this and close this issue.

One thing that would also speak against storing this in Joomla would be, that sites without any interactive elements except for this contact form (like my own website for example) would then have to set up the whole privacy component. Right now a person could request all the data that I have about it and I would only have to go through the stuff on my local system. When you are storing this data in Joomla, you would have to provide that export, too.

So, nothing to do here, at least for now. We could revisit this issue when there are the first few decisions by courts.

**Comment by jeckodevelopment** [comment]
Personally, i don't think we should store the consent in the Privacy dashboard.
Pursuant the Italian Law, before GDPR, there was a similar "consent" mechanism that each website should have implemented and generally it has been done through a checkbox at the end of the contact form (obviously people used third-party extensions to achieve this).
The checkbox was something similar to "I agree with the Privacy Policy of this website" and this sentence was copied also in the email sent to the administrator.
Something like this has been mandatory in Italy (at least) from several years. 
According to GDPR, consents must always be explicit, clear, with clear purpose and so on... so even if i agree with you that if i contact you, i'm implicitly consenting you to process the data i submit, it would be good, if we can add to the email the consent sentence.

**Comment by mbabker** [comment]
> it would be good, if we can add to the email the consent sentence.

It would be nice.  Our system capabilities do not allow us to do so without hardcoding com_contact to be dependent on the single privacy consent plugin that we ship in core.  We do not have a hook to alter emails when they are being sent in core, and arbitrarily adding the string to the email would be factually incorrect if you do not have any form of consent in place when submitting it.

**Comment by jeckodevelopment** [comment]
> Our system capabilities do not allow us to do so without hardcoding com_contact to be dependent on the single privacy consent plugin that we ship in core.

I fully understand this. And what about extending com_contact instead of using the plugin?

**Comment by mbabker** [comment]
The only other option is to remove the consent plugin and put options in every component to do the same thing that the consent plugin is doing.  Then, because the options are within the component, could you alter the email body string conditionally without breaking any system rules.

**Comment by jeckodevelopment** [comment]
> The only other option is to remove the consent plugin and put options in every component to do the same thing that the consent plugin is doing.

For the contact form, i believe that would be appropriate and would satisfy the requirement.

**Comment by brianteeman** [comment]
1. this is not a gdpr solution
2. This is just to help you along the way
3. We can never address every countries unique interpretation of a law
4. What were italian web sites doing before

**Comment by mbabker** [comment]
Making any changes for this specific if/else condition IMO opens too many cans of worms to reliably manage, because the scope of work I see it creating ends up in creating a lite version of com_content in com_privacy to have a single spot in core to define and manage the privacy policy (because you can't reasonably force com_contact to only support a com_content created privacy policy article).

**Comment by jeckodevelopment** [comment]
> What were italian web sites doing before

Using different contact forms components.

**Comment by Hackwar** [comment]
You are giving explicit consent to this when checking the checkbox. You are logging if the plugin is active in our actionlog. So you can say "The user had to check the checkbox, otherwise the mail wouldn't have been sent and the checkbox was built in and working, because we have the enabling/disabling of the plugin logged in our log."

**Comment by linuxpac** [comment]
@jeckodevelopment
You can solve the problem by using the custom fields in this way ...

1 - Create a new group of "mail" type fields and name it "Privacy policy".

2 - Create a new additional field of type "mail" as follows:

Title > I declare that I have read and accepted the following Privacy policy

Type > Checkboxes

Required > Yes

Text > By sending us a message through this form, or by directly using the e-mail address indicated here, the processing of your personal data will be carried out in compliance with the EU Regulation 2016/679. The personal data you have provided may be processed in compliance with the aforementioned legislation. The Data Controller, in compliance with the Regulations, will take care of archiving for purposes consistent with the interactions shown by the Visitor and only for the time strictly necessary for the verification and evaluation of the information provided, for the purpose of exchanging information or contacts. To find out more about our privacy policies, please see the extended information at https://www.XXXXXXXXXXXXXXX/privacy. To request information, changes, or to oppose the treatment and request the cancellation of your data, present in our archives, you can write to us via the address XXXXXXXXXX@XXXXXXX.XX.

Value > The same policy entered in Text

Field Group > Assign the previously created group "Privacy policy".

Go to the Permissions tab and set this...
Edit Custom Field Value > Allowed

In this way, the privacy policy will be visible on the contact page, but will also be contained in the email.

**Comment by jeckodevelopment** [comment]
thanks @linuxpac , but i wasn't really looking for a solution for that :)
My suggestion was to implement the opportunity to add the statement into com_contact. 
Anyway, if you guys think that it's not necessary, feel free to close the issue.

**Comment by linuxpac** [comment]
Ok, jeckodevelopment. However, this solution works well and also allows you to demonstrate that the visitor has read and accepted the policy (if you have activated the function "Send Copy to Submitter", even the sender will receive the email containing the declaration of acceptance of the policy with the policy itself).

**Comment by ReLater** [comment]
It's easy to add such a phrase to the email body of the contact form with a small 3rd plugin. I didn't think too much about it but something like this should work:
```
 public function onSubmitContact(&$contact, &$data)
 {
  if (JPluginHelper::isEnabled('content', 'confirmconsent'))
  {
   if (isset($data['consentbox']) && !empty($data['consentbox']))
   {
    $data['contact_message'] .= "\n\n" . 'The user accepted the privacy policy to process this request on DATE';
   }
   // Nearly impossible(?):
   else
   {
    // Say this 
   }
  }
  else
  {
   // Say that
  }
  return true;
 }
```

**Comment by mbabker** [comment]
Closing this out.  Given the core architectural changes needed to properly support this it is too far out of scope to include here, and as pointed out it is possible to add this statement via plugin if so desired.

**Comment by jeckodevelopment** [comment]
Thanks
