### ISSUE TITLE
Direct download link after Log-In

### ISSUE THREAD

**Issue by jjsjjs** [joomla-projects/privacy-framework#218]
### Is your feature request related to a problem? Please describe.
I've been checking out the new Privacy tool. I have many older people who already have difficulty requesting a new log-in password. Although this looks very safe and promising. For these older people it is too difficult. Logging in, requesting a token, go back to email, click something or copy/paste the token. They already stop by putting in their email adres again. I get many many complaints from older people who already as i said can't get a new password. But for us younger people it's so simple.
edit--The same counts for extending the consent.
### Describe the solution you'd like
A direct download available once a user is logged in. We as organization already know who can register and is manually approved. For more open sites where anyone can register the token idea is good. So a choice between providing a direct download or via token would be good.
edit--Also extending the consent would be great if this just goes to a page where the registered could click a simple button. 
The same simple thing i did with using a form to get the consent of all our users, simply read and click agree or not agree.

**Comment by jjsjjs** [comment]
I understand what you are saying. But what if you do not have these tools and someone who is registered makes the direct request to admin. It would be the same as if a download link becomes available after a logged in request, because you can see from who the request is coming from right? 

I also understand that you can use the token as some kind of extra check so you know the person requesting it is in fact the rightfull person. But if someone is logged in then in fact it already should be the rightfull person. So the token check could be seen as some kind of ID check.
Then i checked the rules on Right on insight of personal data, there is no where stated that it should be validated(at least i can't find it, according the Dutch Autihority it should be in article 15 of the gdpr), but that organisations may request some kind of validation. Even requesting a copy of an ID is still not saying if it is the correct person. This is no way to be offensive, just be able to get an easy option if it is not unlawfull. Maybe you can point me to where it is stated that the request has to be validated?  And besides this i appreciate all you guys and dolls do.

**Comment by mbabker** [comment]
> But what if you do not have these tools and someone who is registered makes the direct request to admin. It would be the same as if a download link becomes available after a logged in request, because you can see from who the request is coming from right?

There is no download link ever given to the user.  Core supports directly emailing its export to the user (only triggered by the site admin clicking the button) or the site admin downloading the export to be provided by their own means.  So unless you have super user access, you will never see a download link in the Joomla UI.

As for direct request to admin, again it is a security risk to just allow the admin to action this without confirmation.  If I phone or email you and you enter the request through the admin interface, I still have to perform the verification step.  Imagine a social engineering scenario where someone tricks you to gain information about a user.  That is in part what the verification step helps to prevent.

If you have a userbase where this type of verification step is "too complex", unfortunately this system isn't going to be for you.  Any type of core option to bypass the account verification step is IMO a major security risk to someone's personal data and not a risk that we should be willing to accept with the core software.

**Comment by brianteeman** [comment]
I am closing this. It is absolutely essential for security purposes to ensure account verification for this type of feature.

**Comment by jjsjjs** [comment]
Ok understood. Thanks for the explanation. I will create an step by step explanation for the user who does not completely understand  what is going to happen and what is expected. Thanks a lot for your thought's.
