### ISSUE TITLE
Privacy Policy Module

### ISSUE THREAD

**Issue by Septdir** [joomla-projects/privacy-framework#23]
What do you think about the privacy policy module?

## Concept
Modal window blocking site with privacy policy text and two buttons "Accept" "Refuse"

Displays under conditions
If there is no cookie record for example `privacyPolicy = '2018-05-08'`

Сookie  Value = the date the text was last modified / version

If the user is not a guest then check whether the new policy has adopted privacy policy  set cookie. 

---
I have a notification module and it will not be difficult to redo it for this task.

It remains only to understand where the text itself is stored.

**Comment by mbabker** [comment]
I'm not sure how I feel on this yet, because in essence this is proposing that core has some form of cookie consent tool built into it.  Maybe with the way laws are changing we need to consider that, but for now I'd consider this a lower priority to the other items already open here.

**Comment by Septdir** [comment]
@mbabker I agree on the priority. Just saw several sites, after changing the policy immediately after logging in appears a modal window with a request to accept the change.

**Comment by brianteeman** [comment]
After logging in is a very different scenario (and doesnt need cookies)

**Comment by Septdir** [comment]
@brianteeman I'm not sure that the withdrawal of the privacy policy with the requirement to accept is needed only by a registered user. All the same sites can store and process a lot of data and guests.

If create notification only for registered user.  Сan make a plugin.

And you can not add anything like this to the core. Then there will be a lot of extensions from JED times. The main thing is that the text itself stored somewhere in Joomla (not in com_content)

**Comment by Septdir** [comment]
@mbabker 
 > Like pointed out in #5 I'm not entirely sure yet we should have the privacy policy text management in this component. 

I can give reasons why it is more convenient to do this in a separate component.
But this is not the topic of this Issue. Although it is modules or plugins that require text data, a very powerful argument.

> You aren't necessarily agreeing to the privacy policy though. Usually you're agreeing to an explicit action (user monitoring/tracking via cookies) ...

I like how it's described here  
https://techblog.bozho.net/tracking-cookies-gdpr/


Anyway, I agree that this isusie ( #23 ) is not so important for the current moment. But to write down everything so that you do not forget all the same after all.

**Comment by mbabker** [comment]
This workflow can be done with what's merged in here, just not exactly as described (it's all based on the plugin being enabled and forcing redirects to user profile to accept it before going on).
