### ISSUE TITLE
Inconsistent way of managing the consents state by 'namespacing' it

### ISSUE THREAD

**Issue by joeforjoomla** [joomla-projects/privacy-framework#242]
The table #__privacy_consents should be supposed to include consents managed directly by the core Privacyconsent plugin for the Joomla user component but not limited to this. Consents could/should be even added by third-party extension in the future and as soon as developers will start to integrate their extensions.

At the moment the column to identify the 'extension' storing the consent has not been included, so everything is limited to the 'subject' used to recognized 'who' stored the consent record. In the standard case it's set as an untraslated string: 'PLG_SYSTEM_PRIVACYCONSENT_SUBJECT'

There are some inconsistencies for example in the function `invalidateExpiredConsents ` that uses the condition filter:

`->where($db->quoteName('subject') . ' = ' . $query->quote('PLG_SYSTEM_PRIVACYCONSENT_SUBJECT'))`

to select records to invalidate and the function `isUserConsented ` that instead select all records having 'state = 1' based only on the user id.

**THE PROBLEM**
Let's say that a third-party extension stores a given consent having 'state = 1', a discrepancy bubbles up when using the timed expiration.

Indeed the `invalidateExpiredConsents` invalidates only records having subject:'PLG_SYSTEM_PRIVACYCONSENT_SUBJECT' but other records added by third-party extensions will continue to have the 'state = 1'. The result is that the timed expiration won't work, indeed the `isUserConsented ` will continue to see a valid consent and never will ask again to the user to accept.

**THE SOLUTION**
Feel free to propose the solution, probably it would be enough at least to add 'namespacing' 
`->where($db->quoteName('subject') . ' = ' . $query->quote('PLG_SYSTEM_PRIVACYCONSENT_SUBJECT'))`
to the `isUserConsented ` function or even invalidating all consents despite of the subject in the `invalidateExpiredConsents` so that even third-party consents would be invalidated.

Feel free to propose.

**Comment by alikon** [comment]
pr are welcome

**Comment by joeforjoomla** [comment]
That's great @alikon i will prepare a PR tonight

**Comment by alikon** [comment]
i'd just suggest you to do your pr against the 3.9-dev branch

**Comment by joeforjoomla** [comment]
PR against the 3.9 branch is here https://github.com/joomla/joomla-cms/pull/22047

**Comment by brianteeman** [comment]
thanks
