### ISSUE TITLE
remindExpiringConsents only reminds the 'first' record

### ISSUE THREAD

**Issue by joeforjoomla** [joomla-projects/privacy-framework#243]
### Steps to reproduce the issue
Try to notify more than one expired consent.

### Expected result
All expired consents are cycled and notified by email, additionally all records have 'remind' set to '1' after the notification.

### Actual result
Only the first record is notified, indeed the foreach ($users as $user) {....} has a 'return true' inside it so the loop returns after the first iteration.

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/22028
