### ISSUE TITLE
[feature/logging] How to support third party plugins?

### ISSUE THREAD

**Issue by joomdonation** [joomla-projects/privacy-framework#31]
We need to find out how to allow loggin actions from third party extensions. Something come up in my mind:

1.  If extension just uses core event triggers like **onContentAfterSave**, **onContentAfterDelete**, then they will only has to insert some records related to the extension into two tables: **#__user_logs_extensions**,  **#__user_logs_tables_data**. The only thing we have to do is decide where the log related language items from that extension is stored so that we can load it to translate the message

2. If extension uses custom event trigger (for example, when someone makes an order in a shopping cart extension), they will have to write custom plugin to save data into #__user_logs table. Some questions related to this:

- Should we introduce a new plugin group for these plugins like userlogs or actionlogs? If we introduce a new plugin group, we will have to import this plugin group somewhere in our current system user logs plugin. Also, in this case, should we move our current logs method to a separate plugin like joomla and move it into this new plugin group, too?
- How do we allow these plugins re-use our addLogsToDb method (basically, store data into database and send notification emails to users choose to receive log messages). Move these methods to component model?

**Comment by mbabker** [comment]
Go the plugin route and build some support infrastructure to make that easier (similar to Smart Search or Custom Fields plugins).  While it means there are more extensions in the system, we can't at a core level really try to do everything on behalf of everyone, the best we can do it make it easy to hook into the system and have things just work.

**Comment by joomdonation** [comment]
Can we introduce a new plugin group like actionlogs (same as fields, search, finder...)? Then related to user action logs, we will have:

1. A system plugin (as how we are having at the moment)
2. The code which record action logs related to Joomla core will be moved into a new plugin, we can call it joomla or core and put it inside that new plugin group
3. Thid party extensions can add new action logs plugin for their extension and have these plugins inside actionlogs group, too

Is that the right direction?

**Comment by mbabker** [comment]
> Is that the right direction?

Yes.

**Comment by joomdonation** [comment]
Great, thanks. That's all I need to know now.

**Comment by joomdonation** [comment]
Added PR https://github.com/joomla-projects/privacy-framework/pull/38
