### ISSUE TITLE
Fix Sample Data

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#44]
When all is said and done here make sure that when installing sample data everything is still correct.  IIRC that's mainly the asset and menu stuff.

**Comment by alikon** [comment]
done for com_privacy, com_actionlogs, mod_latestactions with 0e70cbf thru e9320ae in #20

**Comment by mbabker** [comment]
It's all caught up for now.  Keeping open to remember to do one last check when merging to main.

**Comment by alikon** [comment]
you'll find on users menu

**Comment by manojLondhe** [comment]
Oops! my bad. Thanks!
