### ISSUE TITLE
Privacy Dashboard

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#5]
There should be a `com_privacy` admin component which contains some form of dashboard with key metrics (also extensible by plugins) or to help guide users to implementing missing things (i.e. a sanity check that a privacy policy is published).

**Comment by tonypartridge** [comment]
We could add a section in this component to specify the privacy policy? Wondering if having a single privacy policy config area? And then create a menu item for privacy policy instead of using com_content? Idea is to try and keep it in one place?

**Comment by mbabker** [comment]
For MVP I think that's too much personally.

Yeah I do think it'd be interesting if `com_privacy` was the privacy policy manager, but I also worry about what kinds of cans of worms we open if we try to have a page/content management in this block that isn't part of `com_content` (especially as it means the component frontend has to get smart about all the multilingual capabilities).

**Comment by tonypartridge** [comment]
Makes sense, was just trying to provide a single solution.

**Comment by Septdir** [comment]
## Concept
### Admin list view
Version | Users | Date | Language | id
--- | --- | --- | --- | ---
1.2.3 | 9/30 | 2018.05.05 | en de fr | 3
1.1.9 | 30/30 | 2018.04.20 | en de fr | 2
1.0.0 | 30/30 | 2018.04.01 | en de fr | 1

### Admin Item view
One editor for each language. Save to database in one column in JSON format

So we deduce the list of users who did not accept the privacy policy


### Front Item view
Display the contents of the desired language. If the text is empty, we display the contents for the default language

These are just ideas no more.

**Comment by garstud** [comment]
Based on the actual com_privacy request system. Does it make sense to have a dashboard module like this one ?
![capture_2018-05-27_num03](https://user-images.githubusercontent.com/970021/40590386-113561c2-61fe-11e8-8c6f-a03ac79e26fc.png)
* the title displays the total number of requests in work
* 2 badges for each type of request (one in yellow to count the 'pending' requests, and one in red if there is 'confirmed' requests to threat or grey if no request to threat)
* in the footer of the module, a button with the whole total of requests (including 'invalid' and 'completed' requests)
All badge/button is clickable and display the filtered list of requests.

It's just a suggestion. Any comments ?

**Comment by mbabker** [comment]
Reading and rethinking things across the repo, with everything that's been merged so far and #53 plus #51 pretty much ready (meaning most capabilities for MVP are in place, the only thing not started is the data removal framework), we're probably at a point where some form of dashboard and module are ready to build.

`com_privacy` should default to a dashboard view that has all sorts of data (reactionary based on plugins reporting whether a feature is enabled, that way we don't hardcode add-on capabilities to specific plugins):

- The requests "module" (which honestly could almost be its own module extension that someone could add to the admin dashboard if desired), scoped out pretty similar to @garstud screenshot
    - Have some kind of warning for requests over X days old, IIRC GDPR requires a response within 30 days so to me perhaps we could have two checks, one for requests over 14 days old needing attention and one for over 30 days old
- Site health check and dstats
    - Is a privacy policy published (use a `onPrivacyCheckForPolicy` type event since we don't have a setting for this in the component and it allows plugins to report the capability)
    - Number of users who've consented to policy if that system is enabled
    - Check if there's a frontend menu item for at least the request form, less as a hard requirement and more as a "hey we suggest you add this to make this step a little easier for your users" type thing

**Comment by alikon** [comment]
not exactly as proposed by @garstud https://github.com/joomla-projects/privacy-framework/issues/5#issuecomment-392364017, but something similar....

regarding this ...
> Have some kind of warning for requests over X days old, IIRC GDPR requires a response within 30 days so to me perhaps we could have two checks, one for requests over 14 days old needing attention and one for over 30 days old

can be done with  via quickicon plugin, sounds reasonable ?

**Comment by mbabker** [comment]
Between #77 #78 and #92 all sane things are covered here.
