### ISSUE TITLE
Store user consent from the ConfirmConsent plugin?

### ISSUE THREAD

**Issue by garstud** [joomla-projects/privacy-framework#54]
### Is your feature request related to a problem? Please describe.
In GDPR, it seems that any user consent **must be recorded so we can proof** he has give his consent on special action. isn't it?

### Describe the solution you'd like
The ConfirmConsent content plugin use **dynamic custom field** to add a mandatory checkbox to ask the user about his consent !
But, due to the dynamic aspect of the field,  **this consent is not store in Joomla**.
- Does it make sense to add the recording of each consent (at least in a dedicated log) ?

**Comment by mbabker** [comment]
Let's get #20 worked out first because there are a few things that could/should be logged and using that would be the best way to go about it.

**Comment by brianteeman** [comment]
The consent IS stored together with the date and time, browser and ip

**Comment by brianteeman** [comment]
See https://github.com/joomla-projects/privacy-framework/pull/49

**Comment by JoomliC** [comment]
@brianteeman I think @garstud speaks about the plugin content consent for contact and email forms https://github.com/joomla-projects/privacy-framework/pull/12 ;-)

In case of contact/email sending, there's no storing of the data in Joomla site database, so a bit different. So i agree with @mbabker to use action logs for this task, when main PR will be ok.

**Comment by brianteeman** [comment]
well you cant store anything of any value on an anonymous contact form - the fact that its a required field means that you consented in order to send the email.

**Comment by mbabker** [comment]
Even if we don't do the logging ourselves as long as there's a plugin event being fired off when the contact form is submitted someone could easily hook it in.  My main concern is the option is there, whether we include it or leave it to plugins is to be determined.

**Comment by JoomliC** [comment]
> you would just be logging useless data
 
I agree too! (about contact form)
And i don't think the checkbox is required by GDPR for a contact form if data is not stored in database... (when only using Joomla core)
So to be enabled only if a third party extension collect and store those data. In this case, the saving in logs for the consent is required.

For me, about Joomla CMS core, the privacy consent plugin you created for Joomla Users is more a priority #49

**Comment by brianteeman** [comment]
ok - i just dont see the point in logging useless data. it will make using the  real data harder and lead to bloated database
