### ISSUE TITLE
[Logging] Ordering Column?

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#56]
Any particular reason there/s an ordering column in the first column of the table?  Doesn't seem like you'd be manually ordering log messages and the database has no storage of item ordering.

<img width="1440" alt="screen shot 2018-05-30 at 9 27 59 pm" src="https://user-images.githubusercontent.com/368545/40757916-6ffb8d86-6450-11e8-9f11-da277dbdfaab.png">

**Comment by joomdonation** [comment]
Guess it was there by mistake and should be removed. As you said, we would not manual ordering the messages and we also don't have ordering field in the table

**Comment by mbabker** [comment]
Addressed by #60
