### ISSUE TITLE
[General] Language Review

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#57]
Before merging to core, go over the added language strings.

**Comment by brianteeman** [comment]
ping me when this is ready for a final review - ie everything is merged and ready

**Comment by mbabker** [comment]
If you don't see an open issue or PR related to it then consider it unreported and either open an issue or submit a PR.  With well over 12,000 added lines of code there's bound to be something missing.

**Comment by duksh** [comment]
I'd like to help with the English review and translation to French
