### ISSUE TITLE
Email Consent

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#6]
I'm not crystal clear on this requirement, but a lot of contact forms are now getting a data processing consent checkbox.  This should be considered, as well as supplemental actions around it (logging consent).

**Comment by zero-24** [comment]
I have written a very light plugin to do this: https://github.com/zero-24/plg_content_consentbox I'm happy to contribute that to the core. Or do you want to have a field in com_contact for this?

**Comment by mbabker** [comment]
Depending on how this applies it'll also need to cover the mail to capability (as it is an email form).  So a plugin is probably a good way to go here, unfortunately we can only make the plugin target specifically named forms and it wouldn't be able to be more generically hooked into.

**Comment by mbabker** [comment]
I'd do it with language strings.  There's already a system in core for this (overrides UI), no point in trying to duplicate it in another way.

**Comment by brianteeman** [comment]
language strings is really the only option that certain people will approve although I dont like it as its limiting in a single language environment. It's not ideal but as they say in france c'est la vie

**Comment by zero-24** [comment]
Well there could be a option in the plugin where you can set the text to be showed when no language strings are defined.

When i'm back at the hotel i can build a proposal & PR for that so you can give feedback on that.

**Comment by zero-24** [comment]
You can find here the initial PR: https://github.com/joomla-projects/privacy-framework/pull/12 lets discuss there the next steps like how to handle the content of the strings.

**Comment by osworx** [comment]
Lastest expert opinions from several reputated Laywer (Germany) comes to this conclusion:
if you have a Contact Form and its purpose is only to contact someone (e.g. the siteowner) to ask something, no checkbox shall be shown, no consent is required.
On the other hand, if you open up a (new) support ticket, a consent should be given - because you are storing and collecting personal datas.

Maybe that helps a bit ..
