### ISSUE TITLE
Menu location

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#74]
I realised today that we need to add com_privacy and com_logs to the menu presets

administrator\components\com_menus\presets\joomla.xml

Before I do that are you happy that both of these live in the components menu?

I was thinking that com_privacy is user related and could live on the Users menu and that com_logs could live in the Extensions menu

Thoughts?

**Comment by mbabker** [comment]
I'm not tied to any particular spot in the menu for either component right now.  For me I just went with minimum effort to get com_privacy installed and visible, I'd say finding them a "proper" home and adjusting from there makes sense.

**Comment by alikon** [comment]
for com_privacy, it can live in the users menu, and it make sense to me
less sense for com_logs in the extensions menu

**Comment by brianteeman** [comment]
I have done #75 to move the privacy menu to the users dropdown

Now that I have done that it seems logical that user_action_logs also moves there

Thoughts?

**Comment by mbabker** [comment]
They seem to go together, move it there too.

**Comment by brianteeman** [comment]
Ok will do

**Comment by brianteeman** [comment]
Closed see #75
