### ISSUE TITLE
TOS plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#76]
Now that we have a dedicated privacy consent plugin should we also have a dedicated Terms of Service plugin.

Currently to achieve this you have to use the user profile plugin and disable 30 options.

It wouldnt need to be as complex as the privacy consent plugin as it probably wouldnt need to have the redirect code or even the logging.

**Comment by mbabker** [comment]
Makes sense to me.

**Comment by brianteeman** [comment]
So just a content plugin. No logging or redirect stuff

**Comment by brianteeman** [comment]
Closed see #83
