### ISSUE TITLE
Time based consent

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#8]
From discussions online it appears that some countries are suggesting that you specify how long you hold the data for and in some cases are making a recommendation of for example 2 years. So I guess if this framework is to satisfy those people then it will need not only the ability to set a timelimit but also the ability to deal with expiring/expired consent.

**Comment by webgras** [comment]
yes, setting a timeline and decide what to do before expiring and after expired consent - remind? delete? inform?

**Comment by alikon** [comment]
ok let's do this now (cause we currently have a quite good number of tools already in place)

we already know the time when  users have given us their privacy consent
https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/installation/sql/mysql/joomla.sql#L1699

so what still need to be done ?

define the `expired consent timeframe`  param  it could be a new com_privacy setting ?

when consent has expired what we should do ?

- send a remind email to the user and reset/delete the correspondent `#__privacy_consents` item 
or
....

**Comment by brianteeman** [comment]
that sounds about right

**Comment by mbabker** [comment]
Addressed by #121
