### ISSUE TITLE
Tracking Information Requests

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#9]
Something that is going to help site administrators is an ability to track information requests (and this will tie in pretty closely to #3 and possibly other actions as things go).  We should have an interface for tracking the status of requests (generically this can cover requests for a user's information and requests to be deleted as a starting point) and as tools build up around it integrate those into the interface (i.e. if we are able to provide an automated download for #3 then the action for this would come from this view).

Note that this should be able to support requests for users with accounts on the site and what would essentially be guest accounts (as there would be ways for an unauthenticated user to interact with the site and have data in place falling under a rightful request to be forgotten/deleted, such as comments on a blog post).

WIP feature branch for this action: `feature/requests-list`

**Comment by brianteeman** [comment]
it will be important that these requests are permanently logged

for example
person x requests their information be deleted on 1 march
we reply that it cant be because of legal reasons such as tax reporting
x requests again on 1 april, 1 may, 1 june etc

**Comment by mbabker** [comment]
I don't intend on exposing a delete button in this context.

Once completed, information such as a request's status, created date, acted on person/date (essentially whomever marked a request as invalid, complete, or something that would equate to a "closed" workflow transition) will be included in this list.

**Comment by mbabker** [comment]
Migrated to #15
