### ISSUE TITLE
Urgent requests filter

### ISSUE THREAD

**Issue by joomdonation** [joomla-projects/privacy-framework#93]
While testing privacy quick icon plugin, from the dashboard, we only display number of urgent requests and have a link to allow clicking on to see these requests. However, click on the link will display all requests at the moment. So the question is should we add a new urgent requests filter to privacy requests view to allow quick filtering list of requests need to be processed?

**Comment by mbabker** [comment]
IMO that'll cover it.

**Comment by joomdonation** [comment]
It's not exactly urgent requests filter but it's probably OK to have it works like that, so we can leave it as how it's for now
