### ISSUE TITLE
Remove request issue

### ISSUE THREAD

**Issue by alikon** [joomla-projects/privacy-framework#94]
### Steps to reproduce the issue

1.  delete data for user1

create a remove data privacy request for user1
confirm the request
do the delete task on the request

2. delete data for user2

after 1. do the same for user2

### Expected result
the user data are pseudo anonymized

### Actual result
 case 1.

Exception has occurred.
Notice: Undefined index: password2

https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/libraries/src/User/User.php#L657

 case 2.
https://github.com/joomla-projects/privacy-framework/blob/dev/privacy/libraries/src/Table/User.php#L244

email must be unique even for pseudo anonymized user

### Additional comments
for 1.
sorry i've hit the wrong button and committed https://github.com/joomla-projects/privacy-framework/commit/f8917f912ca830f9f1e0fda48aba602e97499e87 instead to make a pr 

please @mbabker kindly review it if the fix is correct

for 2.
i've made a fix via pr #95

**Comment by mbabker** [comment]
https://github.com/joomla-projects/privacy-framework/commit/9d6b734a9f5779fec028b941ce90757abe3d6702 should adequately fix 1, I missed the `empty()` check and coded assuming everything was going through that first path in `User::bind()`.
