### ISSUE TITLE
Diff & Text for CMS Repo Pull Request

### ISSUE THREAD

**Issue by mbabker** [joomla-projects/privacy-framework#98]
Full diff from the work in this repo to the 3.9-dev branch: https://github.com/joomla/joomla-cms/compare/3.9-dev...mbabker:dev/privacy (basically the `dev/privacy` branch here is mirrored to my CMS fork so we have the branch in the main repo's fork network to do a pull request)

Text for the pull request is below

*****

This pull request is the result of a combined effort for introducing a privacy tool suite into Joomla in response to laws and regulations such as GDPR.  Introduced with this pull request are several new extensions and new capabilities in existing APIs to support this work.

### XMLDocument Supports Downloaded Documents

`Joomla\CMS\Document\XMLDocument` presently only supports an inline document disposition, only displaying the document in the browser.  A new `setDownload()` method is added to the class to set whether the document should be downloaded (true) or displayed inline (false).  A new `isDownload()` method is added to check this status.

### com_messages Send Message to All Super Users

We have introduced some notifications with the tool suite that called for sending messages to all super users.  We elected to use the capabilities present in com_messages to support this, and we have added `MessagesModelMessage::notifySuperUsers()` to support this capability.

### Action Logging System

This is the finalization of the ["Recording Action Logs" project from GSoC 2016](https://magazine.joomla.org/issues/issue-aug-2016/item/3111-gsoc-recording-actions-logs-accessible-by-super-admin-status-update), this system provides an infrastructure to create an audit log of activity performed on a website and can be fine tuned to the site admin's preferences.  Extensions are able to hook into this system to add custom messages or have the system process standard CRUD actions.  Work in progress documentation can be found at https://docs.joomla.org/J3.x:User_Action_Logs.

#### Action Logs Component

The component allows site admins to review the action log, export it, and purge entries.

#### Action Logs Plugin

The "Action Log - Joomla" plugin is used to log CRUD actions for supported content related extensions and miscellaneous actions such as extension management.

#### Latest Actions Module

An admin module showing the latest logged actions is available.

### Privacy System

This is the heart of law and regulation related capabilities and provides several subsystems.  Note that this system on its own does NOT make your website compliant with any laws and regulations but is a tool to assist site owners with compliancy.  Work in progress documentation can be found at https://docs.joomla.org/J3.x:Privacy.

#### Privacy Component

The main interaction point for privacy actions and management.  The component offers several functions to help site owners with privacy related matters.

##### Capabilities List

To assist with informing site owners of privacy related capability concerns and data collection, a capabilities screen will display information reported by extensions through a dedicated plugin event.  Unlike other events which are generally targeted to single plugin groups, the model here explicitly imports plugins from several different plugin groups which commonly collect or process data (such as the captcha group as the Google reCAPTCHA integration processes a client's IP address).

##### Consent Tracking

The component supports an audit log tracking all consents given on the web site, in core this is used for the consent plugin (explained later) to track consent to the privacy policy but extensions can log their own consents here as well.

##### Information Requests

Rights given under GDPR and similar privacy regulations include the right to access your data and the right to be forgotten.  The information requests system is used to track and act on these requests.  A request can be created in two ways:

- By a site administrator through the backend
- By a registered user through the frontend

Once the request is confirmed, the site admin will have action buttons appropriate to the request available to them to act upon the request.  Processing for requests is plugin driven, all actions are performed by plugins to allow maximum flexibility and configuration for each affected extension.

#### Privacy Policy Consent Plugin

When enabled, the plugin can be used to mandate that registered users consent to the site's privacy policy (defined in the plugin) before doing anything else on the website.

#### Confirm Consent Plugin

For our email related forms (contact, email to a friend, and the privacy policy form), this plugin adds a consent checkbox to the form for the user to agree to processing the form's information.

#### Terms and Conditions Plugin

When enabled, the plugin can be used to require newly registering users to agree to the site's terms and conditions (defined in the plugin).

#### Privacy Dashboard Module

An admin module showing a summary of the information request data is available.

#### Urgent Requests Notification

A quickicon plugin is available which can be used to alert the site admin to requests which are considered urgent (confirmed and older than the age configured in the component settings, default to 14 days).

#### Log Rotation Plugin

When enabled, this implements a log rotation capability to log files created through the `Joomla\CMS\Log` API and stored to the configured log path, this allows log files to be rotated and removed.

**Comment by brianteeman** [comment]
One small comment

I called it "User - Terms & Conditions" and not terms of service

**Comment by mbabker** [comment]
Updated.

**Comment by brianteeman** [comment]
I think it is better to say "gdpr and similar privacy regulations" instead of just "gdpr"

And to say
This privacy system does NOT make your web site legally compliant, it is just a step in the process.

**Comment by mbabker** [comment]
Pull request sent.  https://github.com/joomla/joomla-cms/pull/20800
